-- Complete PostgreSQL Production DDL, Triggers, and Stored Procedures for Cloud Hosting (Neon/Supabase)
-- Output Generated from pg_dump of fp_mbd local database

-- 1. DROP EXISTING CONFLICTING OBJECTS (Safe Re-run)
DROP TRIGGER IF EXISTS trg_reservasi_status_sync ON reservasi;
DROP TRIGGER IF EXISTS trg_pembayaran_after_changes ON pembayaran;
DROP TRIGGER IF EXISTS trg_layanan_after_changes ON transaksi_layanan;
DROP TRIGGER IF EXISTS trg_detail_res_before_update ON detail_reservasi;
DROP TRIGGER IF EXISTS trg_detail_res_before_insert ON detail_reservasi;
DROP TRIGGER IF EXISTS trg_detail_res_after_changes ON detail_reservasi;

DROP TABLE IF EXISTS transaksi_layanan CASCADE;
DROP TABLE IF EXISTS pembayaran CASCADE;
DROP TABLE IF EXISTS reservasi_pegawai CASCADE;
DROP TABLE IF EXISTS detail_reservasi CASCADE;
DROP TABLE IF EXISTS reservasi CASCADE;
DROP TABLE IF EXISTS pelanggan CASCADE;
DROP TABLE IF EXISTS pegawai CASCADE;
DROP TABLE IF EXISTS kamar CASCADE;
DROP TABLE IF EXISTS layanan_tambahan CASCADE;
DROP TABLE IF EXISTS jenis_kamar CASCADE;
DROP TABLE IF EXISTS shift CASCADE;
DROP TABLE IF EXISTS jabatan CASCADE;
DROP TABLE IF EXISTS status_kamar CASCADE;
DROP TABLE IF EXISTS status_pembayaran CASCADE;
DROP TABLE IF EXISTS status_reservasi CASCADE;
DROP TABLE IF EXISTS metode_pembayaran CASCADE;

DROP FUNCTION IF EXISTS fn_reservasi_status_sync() CASCADE;
DROP FUNCTION IF EXISTS fn_pembayaran_after_changes() CASCADE;
DROP FUNCTION IF EXISTS fn_layanan_after_changes() CASCADE;
DROP FUNCTION IF EXISTS fn_detail_res_before_insert_or_update() CASCADE;
DROP FUNCTION IF EXISTS fn_detail_res_after_changes() CASCADE;
DROP PROCEDURE IF EXISTS sp_sync_reservasi_financials(integer) CASCADE;

-- 2. CREATE MASTER STATUS TABLES
CREATE TABLE status_kamar (
    id_status_kamar integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_status character varying(30) UNIQUE NOT NULL
);

CREATE TABLE status_pembayaran (
    id_status_bayar integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_status character varying(30) UNIQUE NOT NULL
);

CREATE TABLE status_reservasi (
    id_status_res integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_status character varying(30) UNIQUE NOT NULL
);

CREATE TABLE metode_pembayaran (
    id_metode integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_metode character varying(30) UNIQUE NOT NULL
);

CREATE TABLE jabatan (
    id_jabatan integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_jabatan character varying(50) UNIQUE NOT NULL
);

CREATE TABLE shift (
    id_shift integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_shift character varying(30) UNIQUE NOT NULL,
    jam_mulai time without time zone NOT NULL,
    jam_selesai time without time zone NOT NULL
);

-- 3. CREATE CORE ENTITIES
CREATE TABLE jenis_kamar (
    id_jenis_kamar integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_jenis character varying(50) UNIQUE NOT NULL,
    kapasitas integer DEFAULT 2 NOT NULL CHECK (kapasitas > 0),
    harga_master numeric(12,2) NOT NULL CHECK (harga_master >= 0.00)
);

CREATE TABLE kamar (
    id_kamar integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_kamar character varying(10) UNIQUE NOT NULL,
    id_jenis_kamar integer NOT NULL REFERENCES jenis_kamar(id_jenis_kamar),
    id_status_kamar integer NOT NULL REFERENCES status_kamar(id_status_kamar)
);

CREATE TABLE layanan_tambahan (
    id_layanan integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_layanan character varying(100) NOT NULL,
    harga_layanan numeric(12,2) NOT NULL CHECK (harga_layanan >= 0.00),
    status_aktif boolean DEFAULT true NOT NULL
);

CREATE TABLE pegawai (
    id_pegawai integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_jabatan integer NOT NULL REFERENCES jabatan(id_jabatan),
    id_shift integer NOT NULL REFERENCES shift(id_shift),
    nama_pegawai character varying(100) NOT NULL,
    no_telp character varying(20),
    status_aktif boolean DEFAULT true NOT NULL
);

CREATE TABLE pelanggan (
    id_pelanggan integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_lengkap character varying(100) NOT NULL,
    nomor_identitas character varying(30) UNIQUE NOT NULL,
    no_telp character varying(20) NOT NULL,
    email character varying(100),
    alamat text
);

-- 4. CREATE TRANSACTION TABLES
CREATE TABLE reservasi (
    id_reservasi integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pelanggan integer NOT NULL REFERENCES pelanggan(id_pelanggan),
    id_status_res integer NOT NULL REFERENCES status_reservasi(id_status_res),
    tanggal_dibuat timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total_tagihan numeric(12,2) DEFAULT 0.00 NOT NULL CHECK (total_tagihan >= 0.00),
    total_terbayar numeric(12,2) DEFAULT 0.00 NOT NULL CHECK (total_terbayar >= 0.00)
);

CREATE TABLE detail_reservasi (
    id_detail_res integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reservasi integer NOT NULL REFERENCES reservasi(id_reservasi) ON DELETE CASCADE,
    id_kamar integer NOT NULL REFERENCES kamar(id_kamar),
    check_in date NOT NULL,
    check_out date NOT NULL,
    harga_kamar_snapshot numeric(12,2) NOT NULL CHECK (harga_kamar_snapshot >= 0.00),
    diskon_kamar numeric(12,2) DEFAULT 0.00 NOT NULL CHECK (diskon_kamar >= 0.00),
    subtotal numeric(12,2) GENERATED ALWAYS AS (((harga_kamar_snapshot * ((check_out - check_in))::numeric) - diskon_kamar)) STORED,
    CONSTRAINT chk_dates CHECK (check_out > check_in),
    CONSTRAINT uq_res_kamar UNIQUE (id_reservasi, id_kamar)
);

CREATE TABLE transaksi_layanan (
    id_transaksi_layanan integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_detail_res integer NOT NULL REFERENCES detail_reservasi(id_detail_res) ON DELETE CASCADE,
    id_layanan integer NOT NULL REFERENCES layanan_tambahan(id_layanan),
    id_pegawai_pencatat integer NOT NULL REFERENCES pegawai(id_pegawai),
    jumlah integer NOT NULL CHECK (jumlah > 0),
    harga_layanan_snapshot numeric(12,2) NOT NULL CHECK (harga_layanan_snapshot >= 0.00),
    subtotal numeric(12,2) GENERATED ALWAYS AS ((harga_layanan_snapshot * (jumlah)::numeric)) STORED,
    waktu_pesan timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE pembayaran (
    id_pembayaran integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reservasi integer NOT NULL REFERENCES reservasi(id_reservasi) ON DELETE CASCADE,
    id_metode integer NOT NULL REFERENCES metode_pembayaran(id_metode),
    id_status_bayar integer NOT NULL REFERENCES status_pembayaran(id_status_bayar),
    id_pegawai_kasir integer NOT NULL REFERENCES pegawai(id_pegawai),
    nominal_bayar numeric(12,2) NOT NULL CHECK (nominal_bayar > 0.00),
    waktu_pembayaran timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE reservasi_pegawai (
    id_log_pegawai integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_reservasi integer NOT NULL REFERENCES reservasi(id_reservasi) ON DELETE CASCADE,
    id_pegawai integer NOT NULL REFERENCES pegawai(id_pegawai),
    waktu_log timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    keterangan_aktivitas text NOT NULL
);

-- 5. DEFINE DATABASE PROCEDURES AND FUNCTIONS
CREATE OR REPLACE PROCEDURE sp_sync_reservasi_financials(IN p_id_reservasi integer)
LANGUAGE plpgsql AS $$
DECLARE
    v_room_total DECIMAL(12,2) := 0.00;
    v_service_total DECIMAL(12,2) := 0.00;
    v_paid_total DECIMAL(12,2) := 0.00;
BEGIN
    SELECT COALESCE(SUM(subtotal), 0.00) INTO v_room_total FROM detail_reservasi WHERE id_reservasi = p_id_reservasi;
    SELECT COALESCE(SUM(tl.subtotal), 0.00) INTO v_service_total FROM transaksi_layanan tl JOIN detail_reservasi dr ON tl.id_detail_res = dr.id_detail_res WHERE dr.id_reservasi = p_id_reservasi;
    SELECT COALESCE(SUM(p.nominal_bayar), 0.00) INTO v_paid_total FROM pembayaran p JOIN status_pembayaran sp ON p.id_status_bayar = sp.id_status_bayar WHERE p.id_reservasi = p_id_reservasi AND sp.nama_status NOT IN ('Void', 'Refund');
    UPDATE reservasi SET total_tagihan = (v_room_total + v_service_total), total_terbayar = v_paid_total WHERE id_reservasi = p_id_reservasi;
END;
$$;

CREATE OR REPLACE FUNCTION fn_detail_res_before_insert_or_update() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_overlap_count INT;
    v_stay_price DECIMAL(12,2);
BEGIN
    IF (TG_OP = 'INSERT') THEN
        SELECT COUNT(*) INTO v_overlap_count
        FROM detail_reservasi dr
        JOIN reservasi r ON dr.id_reservasi = r.id_reservasi
        JOIN status_reservasi sr ON r.id_status_res = sr.id_status_res
        WHERE dr.id_kamar = NEW.id_kamar
          AND NEW.check_in < dr.check_out
          AND NEW.check_out > dr.check_in
          AND sr.nama_status NOT IN ('Cancelled');
    ELSIF (TG_OP = 'UPDATE') THEN
        SELECT COUNT(*) INTO v_overlap_count
        FROM detail_reservasi dr
        JOIN reservasi r ON dr.id_reservasi = r.id_reservasi
        JOIN status_reservasi sr ON r.id_status_res = sr.id_status_res
        WHERE dr.id_kamar = NEW.id_kamar
          AND dr.id_detail_res <> NEW.id_detail_res
          AND NEW.check_in < dr.check_out
          AND NEW.check_out > dr.check_in
          AND sr.nama_status NOT IN ('Cancelled');
    END IF;
    IF v_overlap_count > 0 THEN
        RAISE EXCEPTION 'OVERBOOKING ERROR: Room already occupied!';
    END IF;
    v_stay_price := (NEW.harga_kamar_snapshot * (NEW.check_out - NEW.check_in));
    IF NEW.diskon_kamar > v_stay_price THEN
        RAISE EXCEPTION 'DISCOUNT ERROR: Discount exceeds stay price!';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_detail_res_after_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        CALL sp_sync_reservasi_financials(NEW.id_reservasi);
    ELSIF (TG_OP = 'UPDATE') THEN
        CALL sp_sync_reservasi_financials(NEW.id_reservasi);
        IF OLD.id_reservasi <> NEW.id_reservasi THEN
            CALL sp_sync_reservasi_financials(OLD.id_reservasi);
        END IF;
    ELSIF (TG_OP = 'DELETE') THEN
        CALL sp_sync_reservasi_financials(OLD.id_reservasi);
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_layanan_after_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_id_res INT;
BEGIN
    IF (TG_OP = 'INSERT') THEN
        SELECT id_reservasi INTO v_id_res FROM detail_reservasi WHERE id_detail_res = NEW.id_detail_res;
        CALL sp_sync_reservasi_financials(v_id_res);
    ELSIF (TG_OP = 'UPDATE') THEN
        SELECT id_reservasi INTO v_id_res FROM detail_reservasi WHERE id_detail_res = NEW.id_detail_res;
        CALL sp_sync_reservasi_financials(v_id_res);
        IF OLD.id_detail_res <> NEW.id_detail_res THEN
            SELECT id_reservasi INTO v_id_res FROM detail_reservasi WHERE id_detail_res = OLD.id_detail_res;
            CALL sp_sync_reservasi_financials(v_id_res);
        END IF;
    ELSIF (TG_OP = 'DELETE') THEN
        SELECT id_reservasi INTO v_id_res FROM detail_reservasi WHERE id_detail_res = OLD.id_detail_res;
        CALL sp_sync_reservasi_financials(v_id_res);
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_pembayaran_after_changes() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF (TG_OP = 'INSERT') THEN
        CALL sp_sync_reservasi_financials(NEW.id_reservasi);
    ELSIF (TG_OP = 'UPDATE') THEN
        CALL sp_sync_reservasi_financials(NEW.id_reservasi);
        IF OLD.id_reservasi <> NEW.id_reservasi THEN
            CALL sp_sync_reservasi_financials(OLD.id_reservasi);
        END IF;
    ELSIF (TG_OP = 'DELETE') THEN
        CALL sp_sync_reservasi_financials(OLD.id_reservasi);
    END IF;
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_reservasi_status_sync() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    v_status_name VARCHAR(30);
    v_occupied_status_id INT;
    v_cleaning_status_id INT;
BEGIN
    SELECT id_status_kamar INTO v_occupied_status_id FROM status_kamar WHERE nama_status = 'Occupied';
    SELECT id_status_kamar INTO v_cleaning_status_id FROM status_kamar WHERE nama_status = 'Cleaning';
    SELECT nama_status INTO v_status_name FROM status_reservasi WHERE id_status_res = NEW.id_status_res;
    IF v_status_name = 'Checked In' THEN
        UPDATE kamar k SET id_status_kamar = v_occupied_status_id FROM detail_reservasi dr WHERE k.id_kamar = dr.id_kamar AND dr.id_reservasi = NEW.id_reservasi;
    ELSIF v_status_name = 'Checked Out' THEN
        UPDATE kamar k SET id_status_kamar = v_cleaning_status_id FROM detail_reservasi dr WHERE k.id_kamar = dr.id_kamar AND dr.id_reservasi = NEW.id_reservasi;
    END IF;
    RETURN NEW;
END;
$$;

-- 6. INDEX OPTIMIZATIONS
CREATE INDEX idx_dates_detail_res ON detail_reservasi USING btree (check_in, check_out);
CREATE INDEX idx_detail_res_id_reservasi ON detail_reservasi (id_reservasi);
CREATE INDEX idx_transaksi_layanan_id_detail ON transaksi_layanan (id_detail_res);
CREATE INDEX idx_pembayaran_id_reservasi ON pembayaran (id_reservasi);
CREATE INDEX idx_kamar_id_jenis_kamar ON kamar (id_jenis_kamar);

-- 7. ATTACH TRIGGERS
CREATE TRIGGER trg_detail_res_after_changes AFTER INSERT OR DELETE OR UPDATE ON detail_reservasi FOR EACH ROW EXECUTE FUNCTION fn_detail_res_after_changes();
CREATE TRIGGER trg_detail_res_before_insert BEFORE INSERT ON detail_reservasi FOR EACH ROW EXECUTE FUNCTION fn_detail_res_before_insert_or_update();
CREATE TRIGGER trg_detail_res_before_update BEFORE UPDATE ON detail_reservasi FOR EACH ROW EXECUTE FUNCTION fn_detail_res_before_insert_or_update();
CREATE TRIGGER trg_layanan_after_changes AFTER INSERT OR DELETE OR UPDATE ON transaksi_layanan FOR EACH ROW EXECUTE FUNCTION fn_layanan_after_changes();
CREATE TRIGGER trg_pembayaran_after_changes AFTER INSERT OR DELETE OR UPDATE ON pembayaran FOR EACH ROW EXECUTE FUNCTION fn_pembayaran_after_changes();
CREATE TRIGGER trg_reservasi_status_sync AFTER UPDATE ON reservasi FOR EACH ROW WHEN ((old.id_status_res IS DISTINCT FROM new.id_status_res)) EXECUTE FUNCTION fn_reservasi_status_sync();

-- 8. DATA SEEDING (DEFAULT SEED FOR DEPLOYMENTS)
INSERT INTO status_kamar (nama_status) VALUES ('Available'), ('Occupied'), ('Cleaning');
INSERT INTO status_pembayaran (nama_status) VALUES ('DP'), ('Pelunasan'), ('Void'), ('Refund');
INSERT INTO status_reservasi (nama_status) VALUES ('Confirmed'), ('Checked In'), ('Checked Out'), ('Cancelled');
INSERT INTO metode_pembayaran (nama_status) VALUES ('Cash'), ('Bank Transfer'), ('Credit Card'), ('E-Wallet');

INSERT INTO jabatan (nama_jabatan) VALUES ('General Manager'), ('Receptionist'), ('Housekeeping'), ('Cashier'), ('F&B Service');

INSERT INTO shift (nama_shift, jam_mulai, jam_selesai) VALUES 
('Morning', '06:00:00', '14:00:00'), 
('Middle', '10:00:00', '18:00:00'),
('Evening', '14:00:00', '22:00:00'), 
('Night', '22:00:00', '06:00:00');

INSERT INTO jenis_kamar (nama_jenis, kapasitas, harga_master) VALUES 
('Standard Room', 2, 350000.00), 
('Superior Room', 2, 500000.00), 
('Deluxe Room', 3, 750000.00), 
('Executive Suite', 4, 1500000.00), 
('Presidential Suite', 6, 3500000.00);

INSERT INTO layanan_tambahan (nama_layanan, harga_layanan, status_aktif) VALUES 
('Extra Bed', 150000.00, TRUE), 
('Laundry Express per Kg', 25000.00, TRUE), 
('Breakfast Buffet Room Service', 75000.00, TRUE), 
('Airport Pick-up Service', 200000.00, TRUE), 
('Late Checkout Charge', 100000.00, TRUE);

INSERT INTO pelanggan (nama_lengkap, nomor_identitas, no_telp, email, alamat) VALUES 
('Budi Santoso', '3171012345670001', '08123456789', 'budi.santoso@email.com', 'Jl. Merdeka No. 10, Jakarta'),
('Siti Aminah', '3171023456780002', '08134567890', 'siti.aminah@email.com', 'Jl. Sudirman No. 45, Bandung'),
('John Doe', 'A987654321', '+14155552671', 'john.doe@foreign.com', '123 Baker Street, London');

INSERT INTO pegawai (id_jabatan, id_shift, nama_pegawai, no_telp, status_aktif) VALUES 
(2, 1, 'Andi Wijaya', '08111111111', TRUE),
(2, 3, 'Siska Amelia', '08111111112', TRUE),
(4, 1, 'Hendra Kurnia', '08111111113', TRUE),
(4, 3, 'Rina Permata', '08111111114', TRUE),
(3, 2, 'Joko Susilo', '08111111115', TRUE);

INSERT INTO kamar (nomor_kamar, id_jenis_kamar, id_status_kamar) VALUES 
('101', 1, 1), 
('102', 1, 1), 
('201', 2, 1), 
('202', 2, 1), 
('301', 3, 1), 
('302', 3, 1), 
('501', 4, 1), 
('901', 5, 1);
